runtime:
  cache_dir: ./.cache/antora

site:
  title: Heading to Production with OSSM Lab Guides
  start_page: ossm-labs-guides:ROOT:1setup.adoc

content:
  sources:
    - url: .
      start_path: docs

asciidoc:
  attributes:
    experimental: true
    page-pagination: true

ui:
  bundle:
    url: ./ui/ui-bundle.zip
  supplemental_files: ./ui/supplemental-ui

output:
  dir: ./site

