# Service Mesh Development Environment
# Red Hat Summit 2023

== Part I: Installing the Development environment

[IMPORTANT]
====
*You do not have to execute anything in this part of the lab* as lab instructors have *pre-setup all the required assets for the Travel Agency development environment*, including users, roles, namespaces, apps, service mesh etc. You will create the PROD environment step-by-step in the next scenario. You can inspect at the end of the lab the installation of the development environment by exploring the link:../setup/run-setup-scenario-1.sh[<BROKEN FIX>Install Script]

Reading the following is totally optional and you are urged to move to _Part II_ as soon as possible as we briefly, below, describe the steps the link:/lab-instructions/scenario-1.adoc#userrolepersona-mapping-for-the-dev-environment[<BROKEN FIX>_Travel Agency Enterprise Personas_] would have had to follow in order to deliver such a development environment:
====

=== Actions with role Cluster Admin

1. As openshift administrator (role: `Cluster Admin`) add the `Service Mesh` operators in the OCP Cluster
2. As openshift administrator (role: `Cluster Admin`) once the operators have been successfully installed, create the necessary _Travel Agency_ Namespaces
3. As openshift administrator (role: `Cluster Admin`) create the `Service Mesh Roles`
4. As openshift administrator (role: `Cluster Admin`) create the Service Mesh Users and assign Roles

=== Actions with role Mesh Operator

1. As *emma* (role: `Mesh Operator`) create the `Service Mesh` controlplane namespaces and the `ServiceMeshControlPlane (SMCP)` resource.

=== Actions with role Mesh Developer

1. As *farid* (role: `Mesh Developer`) _Travel Services Domain Owner (Tech Lead)_
** Onboard namespace `dev-travel-agency` to Service Mesh `dev-basic` by adding a `ServiceMeshMember` (`SMM`) resource in `dev-travel-agency`.
** Deploy the Applications in `dev-travel-agency` namespaces

2. As *cristina* (role: `Mesh Developer`) _Travel Portal Domain Owner (Tech Lead)_
** Onboard namespaces `dev-travel-control` and `dev-travel-portal` to Service Mesh `dev-basic` by adding a `ServiceMeshMember` (`SMM`) resource in each namespace for `dev-basic` membership.
** Deploy the Applications in `dev-travel-control`, `dev-travel-portal` namespaces and `Istio` configs to expose Service Mesh services.

=== Final Actions with role Mesh Operator

1. As *emma* (role: `Mesh Operator`) create the Istio `Gateway` resource

IMPORTANT: `OSSM` -like Istio- now offers the ability for the injection of an  *_ingress Gateway_* in the dataplane however for the _Travel Agency_ use case the Architects have selected a *_Self-Service(Restricted)_*  link:/lab-instructions/scenario-1.adoc#user-governance-model[<BROKEN FIX>Model of Operation] where the `Mesh Operator` will be responsible for ingress/egress resource configurations.
