= 고급 라우트 규칙(Advanced Route Rules)
include::_attributes.adoc[]

[IMPORTANT]
.시작하기 전에
====
`tutorial` 네임스페이스에 *VirtualService* 및 *DestinationRule* 이 존재하지 않아야 합니다. 다음 명령어로 확인할 수 있습니다.

[.console-input]
[source, bash,subs="+macros,+attributes"]
----
kubectl get virtualservice{namespace-suffix}
kubectl get destinationrule{namespace-suffix}
----

만약 위 명령어의 결과로 *VirtualService* 또는 *DestinationRule* 이 존재한다면, 다음 명령어를 실행하여 삭제하십시오.

[.console-input]
[source, bash,subs="+macros,+attributes"]
----
./scripts/clean.sh tutorial{namespace-suffix}
----
====

[#canarydeploymentuseragent]
== 사용자 에이전트(User-Agent) 헤더 기반의 스마트 라우팅 (카나리 배포)

내 사용자 에이전트(User-Agent)는 무엇입니까?

https://www.whoishostingthis.com/tools/user-agent/[https://www.whoishostingthis.com/tools/user-agent/]

[NOTE]
====
*user-agent* 헤더는 *Customer* 서비스의 *OpenTracing baggage* 에 추가됩니다. 
여기서부터 이 헤더는 자동으로 모든 하위 서비스로 전파됩니다. 
자동 baggage 전파를 활성화하려면 중간 서비스 모두가 OpenTracing으로 계측되어야 합니다. 
사용자 에이전트의 baggage 헤더는 `baggage-user-agent: <value>` 형식을 따릅니다.
====

[#alltorecommendationv1]
=== Recommendation을 모두 v1으로 설정

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -f link:{github-repo}/{istiofiles-dir}/destination-rule-recommendation-v1-v2.yml[istiofiles/destination-rule-recommendation-v1-v2.yml] -n tutorial{namespace-suffix}
----

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -f link:{github-repo}/{istiofiles-dir}/virtual-service-recommendation-v1.yml[istiofiles/virtual-service-recommendation-v1.yml] -n tutorial{namespace-suffix}
----

[#safaritov2]
=== Safari 사용자를 v2로 라우팅

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl replace -f link:{github-repo}/{istiofiles-dir}/virtual-service-safari-recommendation-v2.yml[istiofiles/virtual-service-safari-recommendation-v2.yml] -n tutorial{namespace-suffix}
----

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get virtualservice -n tutorial{namespace-suffix}
----

Safari (또는 문자열에 Safari가 포함되어 있는 Mac의 Chrome 브라우저)로 테스트하면, Recommendation의 v2 응답만 표시됩니다.

Firefox 브라우저로 테스트하면, Recommendation의 v1 응답만 표시됩니다.

다음 명령을 사용하여 사용자 에이전트 문자열을 변경하여 curl을 통해 테스트할 수도 있습니다. 

:extrap: -A Safari
include::curl_params.adoc[]

:extrap: -A Firefox
include::curl_params.adoc[]

다음 명령어를 사용하여 *VirtualService* 의 구성을 확인할 수 있습니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get virtualservice -o yaml -n tutorial{namespace-suffix}
----

==== Safari 규칙 제거하기

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete -f istiofiles/virtual-service-safari-recommendation-v2.yml -n tutorial{namespace-suffix}
----

[#mobiletov2]
=== 모바일 사용자를 v2로 라우팅

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -f link:{github-repo}/{istiofiles-dir}/virtual-service-mobile-recommendation-v2.yml[istiofiles/virtual-service-mobile-recommendation-v2.yml] -n tutorial{namespace-suffix}
----

다음 명령어를 사용하여 모바일 사용자 에이전트로 curl 요청을 보낼 수 있습니다.

:extrap: -A "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4(KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5"
include::curl_params.adoc[]
==== 정리(Clean up)

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial{namespace-suffix}
----

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete -f istiofiles/virtual-service-mobile-recommendation-v2.yml -n tutorial{namespace-suffix}
----

또는 다음 명령을 실행할 수 있습니다.

[.console-input]
[source, bash,subs="+macros,+attributes"]
----
./scripts/clean.sh tutorial{namespace-suffix}
----

[#mirroringtraffic]
== 트래픽 미러링 (다크 론치)

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get pods -l app=recommendation -n tutorial{namespace-suffix}
----

위 단계에 따라 recommendation Pod가 2개 있어야 합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get virtualservice -n tutorial{namespace-suffix}
----

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get destinationrule
----

`tutorial` 네임스페이스에 *VirtualService* 및 *DestinationRule* 이 없어야 합니다. 
존재하는 경우, 다음 명령을 실행합니다.

[.console-input]
[source, bash,subs="+macros,+attributes"]
----
./scripts/clean.sh tutorial{namespace-suffix}
----

"istio-tutorial"의 메인 디렉터리에 있는지 확인합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -f link:{github-repo}/{istiofiles-dir}/destination-rule-recommendation-v1-v2.yml[istiofiles/destination-rule-recommendation-v1-v2.yml] -n tutorial{namespace-suffix}
----

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -f link:{github-repo}/{istiofiles-dir}/virtual-service-recommendation-v1-mirror-v2.yml[istiofiles/virtual-service-recommendation-v1-mirror-v2.yml] -n tutorial{namespace-suffix}
----

include::curl.adoc[]

recommendation-v2의 로그를 확인합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl logs -f `kubectl get pods -n tutorial{namespace-suffix}|grep recommendation-v2|awk '{ print $1 }'` -c recommendation -n tutorial{namespace-suffix}
----

=== 정리(Clean up)

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial{namespace-suffix}
----

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete -f istiofiles/virtual-service-recommendation-v1-mirror-v2.yml -n tutorial{namespace-suffix}
----

또는 다음 명령을 실행할 수 있습니다.

[.console-input]
[source, bash,subs="+macros,+attributes"]
----
./scripts/clean.sh tutorial{namespace-suffix}
----

[#loadbalancer]
== 로드 밸런서

기본적으로 "라운드 로빈(Round-Robin)" 스타일의 로드 밸런싱이 사용되지만, 
*RANDOM* 옵션을 설정하면 더 뚜렷하게 보일 수 있습니다.

v2 Pod을 하나 더 추가합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl scale deployment recommendation-v2 --replicas=2 -n tutorial{namespace-suffix}
----

조금 기다린 후 (`oc get pods -w` 명령어로 확인 가능) 
여러 번 customer 엔드포인트에 curl 요청을 보냅니다.

include::curl.adoc[]

v2 Pod을 하나 더 추가하여 총 3개의 v2 Pod을 만듭니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl scale deployment recommendation-v2 --replicas=3 -n tutorial{namespace-suffix}
kubectl get pods -n tutorial{namespace-suffix}
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
NAME                                  READY     STATUS    RESTARTS   AGE
customer-1755156816-cjd2z             2/2       Running   0          1h
preference-3336288630-2cc6f           2/2       Running   0          1h
recommendation-v1-3719512284-bn42p    2/2       Running   0          59m
recommendation-v2-2815683430-97nnf    2/2       Running   0          43m
recommendation-v2-2815683430-d49n6    2/2       Running   0          51m
recommendation-v2-2815683430-tptf2    2/2       Running   0          33m
----

Pod의 컨테이너 상태가 `2/2`가 되기를 기다린 후, 
customer 엔드포인트에 반복적으로 요청을 보냅니다.

include::generate_traffic.adoc[]

결과는 일반적인 라운드 로빈 패턴을 따릅니다.

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
customer => preference => recommendation v1 from 'recommendation-v1-6cf5ff55d9-7zbj8': 1145
customer => preference => recommendation v2 from 'recommendation-v2-2819441432-525lh': 1
customer => preference => recommendation v2 from 'recommendation-v2-2819441432-rg45q': 2
customer => preference => recommendation v2 from 'recommendation-v2-2819441432-bs5ck': 181
----

이제 Random LB DestinationPolicy를 추가합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -f link:{github-repo}/{istiofiles-dir}/destination-rule-recommendation_lb_policy_app.yml[istiofiles/destination-rule-recommendation_lb_policy_app.yml] -n tutorial{namespace-suffix}
----

이제 어떤 Pod이 선택되는지에 대한 패턴이 변경된 것을 확인할 수 있습니다.

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
customer => preference => recommendation v2 from 'recommendation-v2-2819441432-rg45q': 10
customer => preference => recommendation v2 from 'recommendation-v2-2819441432-525lh': 3
----

=== 정리(Clean up)

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete -f istiofiles/destination-rule-recommendation_lb_policy_app.yml -n tutorial{namespace-suffix}
----

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl scale deployment recommendation-v2 --replicas=1 -n tutorial{namespace-suffix}
----
