# Setup Travel Demo `ServiceMeshControlPlane` for Production

## ABOUT THIS LAB

The Travel Agency company has a running development environment. Now the company is heading to production. In this scenario you are going to set up Openshift Service Mesh for production use, deploy the travel applications in the Mesh, exposing the application for external access with TLS and fine tune parameters for production.

== Production Requirements

Let us recall the initial requirements for production discussed in scenario 1:

1. The _Development Team_ wants to be able to trace (every) request during development, and a sample of `20%` of traffic in Production
2. The _Development Teams_ wants to implement some resiliency to make the overall application more stable and reliable.
3. The _Product Team_ wants to see metrics around performance/usage (storing them for up to 1 week)
4. The _Security_ team wishes to enable mTLS in all _intramesh_ and _intermesh_ communications
5. The _Platform Team_ wants to centrally manage security

== User/Roles Mapping for the Production environment

For the purpose of managing, monitoring and troubleshooting the Production environment the following Enterprise Personas are involved.

[cols="1,1,3,4"]
.Users created in `PROD` Environment
|===
| Username | Password | Enterprise Persona |  Responsible for Namespace

| emma | emma | Mesh Operator | `%LAB_PARTICIPANT_ID%-prod-istio-system`

| cristina | cristina | Travel Portal Domain Owner (Tech Lead)  | `%LAB_PARTICIPANT_ID%-prod-travel-portal`, `%LAB_PARTICIPANT_ID%-prod-travel-control`

| farid | farid | Travel Services Domain Owner (Tech Lead)  | `%LAB_PARTICIPANT_ID%-prod-travel-agency`

| craig | craig | Platform (Application Ops) Team  | `%LAB_PARTICIPANT_ID%-prod-travel-portal`, `%LAB_PARTICIPANT_ID%-prod-travel-control`, `%LAB_PARTICIPANT_ID%-prod-travel-agency`

| mus | mus | Product Owner | `%LAB_PARTICIPANT_ID%-prod-travel-portal`, `%LAB_PARTICIPANT_ID%-prod-travel-control`, `%LAB_PARTICIPANT_ID%-prod-travel-agency`

|===

[NOTE]
====
The Lab Instructors have already created all production namespaces for your user as well as the Openshift users that will interact with the mesh (including roles and rolebindings) for the production environment. You will now proceed to create the Prod Service Mesh Setup.
====